[  
   [  
      {  
         "name":"somename",
         "triggeredby":"#txt1",
         "runoninitialise":"false",
         "runonsave":"false",
         "runonsaveonly":"false",
         "runoninitialiseonly":"false",
         "message":"General validation message - OVERRIDE",
         "rules":[  
            {  
               "conditiontype":"AND",
               "rules":[  
                  {  
                     "selector":"#txt1",
                     "operator":"equal",
                     "value":"craig"
                  },
                  {  
                     "selector":"#txt2",
                     "operator":"not-equal",
                     "value":"tony"
                  }
               ],
               "actions":{  
                  "tru":[  
                     {  
                        "action":"hide",
                        "selector":"#txt1",
                        "actionmessage":"",
                        "actionset":""
                     }
                  ],
                  "fal":[  
                     {  
                        "action":"show",
                        "selector":"#txt1",
                        "actionmessage":"",
                        "actionset":""
                     }
                  ]
               }
            }
         ]
      }
   ]
]